"""
tools/pptx_generator.py — Generate .pptx presentations using python-pptx.
Student 1 owns this file.

This is the most demo-critical tool. If the agent struggles to call it
dynamically, use demo/generate_summary_ppt.py as a hardcoded fallback.
"""

import os
from datetime import datetime

try:
    from pptx import Presentation
    from pptx.util import Inches, Pt, Emu
    from pptx.dml.color import RGBColor
    from pptx.enum.text import PP_ALIGN
    PPTX_AVAILABLE = True
except ImportError:
    PPTX_AVAILABLE = False


# ── Theme colours ──────────────────────────────────────────────────────────────
DARK_BG    = RGBColor(0x1A, 0x1A, 0x2E) if PPTX_AVAILABLE else None  # deep navy
ACCENT     = RGBColor(0x00, 0xD4, 0xFF) if PPTX_AVAILABLE else None  # cyan
WHITE      = RGBColor(0xFF, 0xFF, 0xFF) if PPTX_AVAILABLE else None
LIGHT_GREY = RGBColor(0xCC, 0xCC, 0xCC) if PPTX_AVAILABLE else None


def _set_slide_bg(slide, color: "RGBColor"):
    """Fill a slide background with a solid colour."""
    from pptx.util import Pt
    from pptx.oxml.ns import qn
    from lxml import etree

    background = slide.background
    fill = background.fill
    fill.solid()
    fill.fore_color.rgb = color


def _add_title_slide(prs: "Presentation", title: str, subtitle: str = ""):
    """Add a styled title slide."""
    layout = prs.slide_layouts[6]  # blank layout — we'll place everything manually
    slide = prs.slides.add_slide(layout)
    _set_slide_bg(slide, DARK_BG)

    # Title text box
    txBox = slide.shapes.add_textbox(Inches(0.8), Inches(2.5), Inches(8.4), Inches(1.5))
    tf = txBox.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.alignment = PP_ALIGN.CENTER
    run = p.add_run()
    run.text = title
    run.font.size = Pt(40)
    run.font.bold = True
    run.font.color.rgb = WHITE

    # Subtitle
    if subtitle:
        txBox2 = slide.shapes.add_textbox(Inches(0.8), Inches(4.2), Inches(8.4), Inches(0.8))
        tf2 = txBox2.text_frame
        p2 = tf2.paragraphs[0]
        p2.alignment = PP_ALIGN.CENTER
        run2 = p2.add_run()
        run2.text = subtitle
        run2.font.size = Pt(18)
        run2.font.color.rgb = ACCENT

    # Bottom watermark
    wm = slide.shapes.add_textbox(Inches(0), Inches(6.8), Inches(10), Inches(0.3))
    tf3 = wm.text_frame
    p3 = tf3.paragraphs[0]
    p3.alignment = PP_ALIGN.CENTER
    run3 = p3.add_run()
    run3.text = "Generated by Offline AI OS  •  AMD Ryzen Powered  •  No Cloud"
    run3.font.size = Pt(9)
    run3.font.color.rgb = LIGHT_GREY


def _add_content_slide(prs: "Presentation", heading: str, bullets: list[str]):
    """Add a content slide with heading and bullet points."""
    layout = prs.slide_layouts[6]
    slide = prs.slides.add_slide(layout)
    _set_slide_bg(slide, DARK_BG)

    # Heading bar
    hdr = slide.shapes.add_textbox(Inches(0.5), Inches(0.3), Inches(9), Inches(0.8))
    tf = hdr.text_frame
    p = tf.paragraphs[0]
    run = p.add_run()
    run.text = heading
    run.font.size = Pt(28)
    run.font.bold = True
    run.font.color.rgb = ACCENT

    # Divider line (thin rectangle)
    slide.shapes.add_shape(
        1,  # MSO_SHAPE_TYPE.RECTANGLE
        Inches(0.5), Inches(1.15),
        Inches(9), Emu(40_000),  # very thin
    ).fill.solid()
    slide.shapes[-1].fill.fore_color.rgb = ACCENT
    slide.shapes[-1].line.fill.background()

    # Bullet text box
    body = slide.shapes.add_textbox(Inches(0.7), Inches(1.4), Inches(8.6), Inches(5.0))
    tf2 = body.text_frame
    tf2.word_wrap = True

    for i, bullet in enumerate(bullets):
        para = tf2.paragraphs[0] if i == 0 else tf2.add_paragraph()
        para.space_before = Pt(6)
        run = para.add_run()
        run.text = f"▸  {bullet}"
        run.font.size = Pt(18)
        run.font.color.rgb = WHITE


def generate_ppt(
    title: str,
    slides: list[dict],
    output_path: str = None,
    subtitle: str = "",
) -> dict:
    """
    Generate a styled .pptx presentation.

    Args:
        title:       Presentation title (shown on cover slide).
        slides:      List of slide dicts, each with:
                       - "heading": str
                       - "bullets": list[str]
        output_path: Where to save the file. Defaults to demo/outputs/<title>.pptx
        subtitle:    Optional subtitle for the cover slide.

    Returns:
        {"success": bool, "path": str, "slide_count": int, "message": str}

    Example:
        generate_ppt(
            title="Research Summary",
            slides=[
                {"heading": "Key Findings", "bullets": ["Finding 1", "Finding 2"]},
                {"heading": "Conclusion",   "bullets": ["It works offline"]},
            ]
        )
    """
    if not PPTX_AVAILABLE:
        return {
            "success": False,
            "path": "",
            "slide_count": 0,
            "message": "python-pptx not installed. Run: pip install python-pptx",
        }

    # ── Default output path ────────────────────────────────────────────────────
    if output_path is None:
        safe_title = "".join(c if c.isalnum() or c in " _-" else "_" for c in title)
        timestamp = datetime.now().strftime("%H%M%S")
        filename = f"{safe_title}_{timestamp}.pptx"
        output_dir = os.path.join(
            os.path.dirname(__file__), "..", "..", "demo", "outputs"
        )
        os.makedirs(output_dir, exist_ok=True)
        output_path = os.path.join(output_dir, filename)

    try:
        prs = Presentation()
        prs.slide_width  = Inches(10)
        prs.slide_height = Inches(7.5)

        # Cover slide
        _add_title_slide(prs, title, subtitle or "Offline AI OS — Local Inference")

        # Content slides
        for slide_data in slides:
            heading = slide_data.get("heading", "")
            bullets = slide_data.get("bullets", [])
            _add_content_slide(prs, heading, bullets)

        prs.save(output_path)
        return {
            "success": True,
            "path": os.path.abspath(output_path),
            "slide_count": len(slides) + 1,
            "message": f"Presentation saved: {output_path}",
        }

    except Exception as e:
        return {"success": False, "path": "", "slide_count": 0, "message": str(e)}


# ── Quick test ─────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    import json, tempfile

    with tempfile.TemporaryDirectory() as tmp:
        result = generate_ppt(
            title="Research Summary",
            subtitle="Generated offline on AMD Ryzen",
            slides=[
                {
                    "heading": "Key Findings",
                    "bullets": [
                        "Local inference is viable on AMD Ryzen",
                        "ONNX Runtime reduces latency by 30%",
                        "No cloud dependency required",
                    ],
                },
                {
                    "heading": "Methodology",
                    "bullets": [
                        "Embedded documents using MiniLM-L6 via ONNX",
                        "Stored vectors in ChromaDB",
                        "Queried with cosine similarity",
                    ],
                },
                {
                    "heading": "Conclusion",
                    "bullets": [
                        "Offline AI OS is production ready",
                        "AMD Ryzen delivers 45ms average inference",
                    ],
                },
            ],
            output_path=os.path.join(tmp, "test_output.pptx"),
        )
        print(json.dumps(result, indent=2))
        if result["success"]:
            print(f"\n✅ Open the file to verify: {result['path']}")